### ISSUE TITLE
Get-AuthToken fails when mfa is expired?

### ISSUE THREAD

**Issue by bartvermeersch** [nicolonsky/AzureADLicensing#4]
The Get-AuthToken function returns an error when creating an Azure session.

Get-AzContext is not null or empty, but getting an API token unfortunately fails.
Is there another check we can perform to trigger Connect-AzAccount

https://github.com/nicolonsky/AzureADLicensing/blob/master/AzureADLicensing/AzureADLicensing.psm1#L260

Get-AuthToken : Exception calling "Authenticate" with "7" argument(s): "Failed to acquire token silently as no token was found in the cache. Call method
 AcquireToken: AADSTS50078: Presented multi-factor authentication has expired due to policies configured by your administrator, you must refresh your mu
lti-factor authentication to access '<GUID>'.

**Comment by nicolonsky** [comment]
To be honest I don't like the approach I implemented with the ```Get-AuthToken``` & ```Test-AuthToken```. Would be nicer to leverage all authentication stuff on the Az module and just forward potential auth issues to the client. So instead of using my custom functions just passing a token from the AzContext to the web requests and catching the 401 / 403 exceptions with a nice error message that you need to authenticate in advance.

I guess calling ```Clear-AzContext``` would solve your issue. But this PowerShell module needs definitely an update. Feel free to submit a PR if you have an idea - otherwise I'll add this to my "to-do" list when I have a little bit more time to spare! Thanks for the feedback by the way!

**Comment by nicolonsky** [comment]
Should be fixed with https://github.com/nicolonsky/AzureADLicensing/commit/b02b672ac9ed9d45cba1ea5f3bfd97424b20140f
