### ISSUE TITLE
Removing disabled plans

### ISSUE THREAD

**Issue by et3rae** [nicolonsky/AzureADLicensing#6]
I am trying to update the disabled plans for a license suite and have tried using the Update command and the Add command to update company:ENTERPRISEPACK to remove all disabled plans
update-aadgrouplicenseassignment -groupid "GUID" -accountskuid "company:enterprisepack"
add-aadgrouplicenseassignment -groupid "GUID" -accountskuid "company:enterprisepack"

both resulted in an error that was not helpful: licenses could not be assigned or removed due to an error.

Is it even possible to change the disabled plans with these commands?

**Comment by nicolonsky** [comment]
Yes, your commands should work. Fixed this (caused by some API changes) in https://github.com/nicolonsky/AzureADLicensing/commit/a8ab1789743bd92273ec28e9659132ce9fd2bcf6 (version 2.3.4 should pop up soon under relases / PowerShell Gallery). The update command without specifying disabled plans enables all plans for a specific SKU.

**Comment by et3rae** [comment]
We have tried this a few times.  We uninstalled the module (twice so that both 2.3.0 and 2.3.4 were uninstalled), then reinstalled the module and ensured we had closed all sessions and disconnected and started fresh with a new PowerShell window, and we still get the same error running
update-aadgrouplicenseassignment -groupid "GROUPGUID" -accountskuid "TENANT:enterprisepack"

update-aadgrouplicenseassignment : Licenses could not be assigned or removed due to an error.
At line:1 char:1
+ update-aadgrouplicenseassignment -groupid "guid ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Update-AADGroupLicenseAssignment

**Comment by nicolonsky** [comment]
Is it possible that your modification has already been performed (manually)? If I try to update a license assignment without changes to the current state I receive the same error (message comes from the API by the way).
As you can see the first time the command succeeds (because there are changes to process), whereas subsequent calls will fail: 
![image](https://user-images.githubusercontent.com/32899754/91768190-8d59e500-ebdd-11ea-9bf4-43f3a5fccc92.png)

**Comment by nicolonsky** [comment]
+ Please make sure that you are connected to the right tenant (also ran into this one recently)... You can verify it by running `Get-AzContext`

**Comment by et3rae** [comment]
We can’t modify via the GUI because the page won’t load (ticket opened with support).  Which is why we were looking via powershell.  The admin I’m working with only has access to their tenant.  And get-azcontext returned their tenant as expected.

**Comment by et3rae** [comment]
Never mind…we found the problem.  Just not the solution yet.

Group based licensing does not work well (at all) with DLs.  Must be security group or mail-enabled security group.
